spring:
  datasource:
    url: jdbc:mysql://${DBHOST}:${PORT}/${DBNAME}
    username: ${DBUSER}
    password: ${DBPASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
        show_sql: true
        format_sql: true